# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Saurabh Shah # ex. I m Chuan
name: Saurabh Shah # ex. DONGChuan
email: shahsaurabh0103@gmail.com
location: Gandhinagar,India # ex. Nice, France
facebook: https://www.facebook.com/saurabh.shah.507
twitter: https://twitter.com/shahsaurabh0605
twitter_handle: shahsaurabh0605
github_username: shahsaurabh0605
company_url: https://github.com/shahsaurabh0605
github_url: https://github.com/shahsaurabh0605 # ex. https://github.com/DONGChuan
description: I like my website
favicon: favicon.png # Image must be in assets/images
repository: shahsaurabh0605/shahsaurabh0605.github.io
# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
#url: http://shahsaurabh0605.github.io
url: http://localhost:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blogs

#  -
#    href: /bookmark
#    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, Ruby, Docker, Travis CI]
skill_web_keywords: [HTML, CSS, Boostrap, JS, MySQL, Ruby on Rails, Jekyll, PHP]
